### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by 14blacktea** [potato-farm/alchera-ai-challenge#12]
학습 데이터와 테스트 데이터 셋이 괴리감이 좀 큰거 같은데,,
EDA가 필요해 보입니다!

**Comment by 8639sung** [comment]
[라벨링 오류 관련]
주어진 데이터의 경우 사람을 기준으로 오른쪽 왼쪽을 정하지만, 제공한 테스트용 데이터는 반대로 라벨링 되어 있는 부분 확인.
일단은 일반적인 기준으로 생각하여, 사람을 기준으로 방향을 정하여 학습.

정확한 라벨링 기준은 알체라에 문의중입니다.
