### ISSUE TITLE
Baseline 구축

### ISSUE THREAD

**Issue by Seyoung9304** [potato-farm/alchera-ai-challenge#14]
trash seg 대회 torch 베이스라인 기반으로
1. base_dataset.py -> 우리 데이터에 맞게수정
2. inference_method.py -> csv형식에서 이미지 형식으로 output 나오게 수정

**Comment by 8639sung** [comment]
- [ ] train.py
- [ ] dataset.py
- [ ] test.py
- [ ] model, swin-t
- [ ] model, swin-s

**Comment by 8639sung** [comment]
Wandb log 수정 필요
기존 trash로 설정되어 있음.

**Comment by 8639sung** [comment]
#18 
진행사항 참고하세요!
