### ISSUE TITLE
File exists error

### ISSUE THREAD

**Issue by rachel318318** [potato-farm/alchera-ai-challenge#21]
모델 훈련할 때 실험 이름이 똑같고 output 폴더가 이미 생성되어 있으면 file exists error가 뜬다
같은 폴더의 이름이 있다면 뒤에 숫자를 붙이는 등 새로운 폴더를 만들어볼까,,?

**Comment by 8639sung** [comment]
구현에 시간이 많이 안걸린다면, 있으면 좋을 것 같아요!
너무 번거롭다면 패스!

**Comment by rachel318318** [comment]
폴더 이름이 같으면 뒤에 index 붙이는 걸로 해결했어용 참고해주세요! dev_base에 푸시했습니다
